smsh4: smsh4.c splitline.c execute2.c process2.c controlflow.c builtin.c varlib.c
	cc -o smsh4 smsh4.c splitline.c execute2.c process2.c controlflow.c builtin.c varlib.c

smsh1-1: smsh1-1.c splitline.c execute.c
	cc -o smsh1-1 smsh1-1.c splitline.c execute.c

clear:
	rm -f smsh1-1 smsh4