
all: play_again0 play_again1 play_again2 play_again3

play_again0: play_again0.c
	gcc -o play_again0 play_again0.c

play_again1: play_again1.c
	gcc -o play_again1 play_again1.c

play_again2: play_again2.c
	gcc -o play_again2 play_again2.c

play_again3: play_again3.c
	gcc -o play_again3 play_again3.c

clean:
	rm -f play_again0 play_again1 play_again2 play_again3



